version: "3.7"
services:
  logcord:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_HOST: mongodb://mongo:27017/logcord
    ports:
      - 8000:8000
    volumes:
      - ./:/app/:ro

  mongo:
    image: mongo:4
    expose:
      - 27017
    volumes:
      - ./mongo_data/:/data/db/

volumes:
  mongo_data:
